### ISSUE TITLE
Drastic slows down when exiting out of sleep mode

### ISSUE THREAD

**Issue by beeg-beeg** [steward-fu/nds_miyoo#17]
When I'm playing a game and entering into sleep mode, after I exit out of sleep mode it slows down tremendously

**Comment by steward-fu** [comment]
May I know which OS system you are using ?
For Onion OS, the development team is doing integration testing for such feature.
It is recommended to wait for the next Onion release for sleep mode support.

**Comment by beeg-beeg** [comment]
I'm using OnionOS 4.2.0 but I'm talking about the sleep mode before shutdown, if I turn on before the shutdown it slows down(I would like to include a video but idk how in github)

**Comment by steward-fu** [comment]
could you please provide the download link to me ?

**Comment by beeg-beeg** [comment]
of the os or video?

**Comment by Ninoh-FOX** [comment]
this because the sleep mode need get the last cpu speed set for drastic and set this again when exit from sleep mode

**Comment by beeg-beeg** [comment]
oh ok thanks for the answer :)
