### ISSUE TITLE
Roms do not load

### ISSUE THREAD

**Issue by AncientPixel** [steward-fu/nds_miyoo#18]
I'm running Drastic 1.6.7 on the Miyoo Mini Plus (Onion OS 4.2.3). When I try and load a ROM I just get a click from the speaker, as if it's switching emulators or something, and then I'm back in the ROM selection screen.
Any idea why?

**Comment by steward-fu** [comment]
For ROM issue, please provide the rom for testing.

**Comment by AncientPixel** [comment]
Sorry this was due to transferring the Drastic emulator to my Miyoo Mini Plus via FTP which somehow broke it, I used the HTTP web based file sync and it worked.
