### ISSUE TITLE
Sound not working after upgrading to fw 202306111426

### ISSUE THREAD

**Issue by axiel7** [steward-fu/nds_miyoo#21]
I upgraded to the latest firmware (from 202204190828 I think) and now the sound is not working. OG MM

**Comment by steward-fu** [comment]
May I know which OS you are using on your device ? is it Onion or Stock system ?
If it is Stock system, please turn off "Audio Fix" in Settings page to see whether it fixed or not.

**Comment by axiel7** [comment]
I'm using Allium. I erased the SDCARD and reinstalled the OS and now it's working fine so I'm closing this
