### ISSUE TITLE
Change the language

### ISSUE THREAD

**Issue by belmix** [steward-fu/nds_miyoo#22]
Changing the language of the application, not through a file (settings.json), by selecting in the menu?

**Comment by steward-fu** [comment]
Yes, I am implementing the function you mentioned.

**Comment by steward-fu** [comment]
commit: https://github.com/steward-fu/nds_miyoo/commit/0fcf19fa8a80515faefdba3ad9e52be39b52afc3

Will be included in the next build v1.7

**Comment by steward-fu** [comment]
v1.7 has been released and included this feature.
