### ISSUE TITLE
How to adapt settings menu enlargement for other projects

### ISSUE THREAD

**Issue by christianhaitian** [steward-fu/nds_miyoo#30]
Hi,

How can the ability to enlarge the Drastic settings menu be adapted for other projects that use SDL2?

Thanks,

**Comment by steward-fu** [comment]
Hello Christianhaitian,
Long time no see :)

I used the hooking point to replace the original settings menu.
Hooking point in here means memory patch and jump to my function for handling settings menu by myself.

Steps:
1. Use Ghidra to reverse DraStic ELF binary to see what is the entry for print_string()
2. Prepare the memory patch: https://github.com/steward-fu/nds_miyoo/blob/master/detour/main.c#L49-L59
3. Call the memory patch: https://github.com/steward-fu/nds_miyoo/blob/master/sdl2/src/video/mmiyoo/SDL_video_mmiyoo.c#L3427
4. Now, when DraStic is drawing the setting menu, it will be redirected into your function: https://github.com/steward-fu/nds_miyoo/blob/master/sdl2/src/video/mmiyoo/SDL_video_mmiyoo.c#L895

**Comment by christianhaitian** [comment]
Thank you Steward.  I'll see how best I can replicate this on my end if possible.
