### ISSUE TITLE
Hotkey and Menu Key not working

### ISSUE THREAD

**Issue by Rastercat** [steward-fu/nds_miyoo#34]
Upgrading from 1.6 to 1.7, Menu key does not work and Hotkeys do not work other than L2 and R2.

Also when adjusting volume it leaves graphical bug where volume came up on overlay. This also happens on 1.6 but you can go into menu and come back out to get rid of it.

**Comment by steward-fu** [comment]
You can change the hotkey binding back to original one from the following steps:
1. go to customized menu
2. change the hotkey bindging with SELECT

hotkey description: https://github.com/steward-fu/nds_miyoo

**Comment by hjferguson** [comment]
I just attempted to use 1.7, and i can't use any custom key combos. Like... select isn't being registered at all. I also can't leave the emulator without booting off the system.

**Comment by hjferguson** [comment]
I deleted 1.7, installed 1.6, and all of the buttons work as expected now. I tried every combo in 1.7 and couldn't reach the custom menu.
