### ISSUE TITLE
Lagging after back from suspend mode (power button)

### ISSUE THREAD

**Issue by steward-fu** [steward-fu/nds_miyoo#37]
I had this problem with v.6 too but I'm playing Solatorobo and when I press the porwe button to pause and then press again the game starts lagging a lot, if I change the cpu to anything it gets back to normal.

Reported from Brave Heart

**Comment by schmurtzm** [comment]
I think that Toto has managed it in Onion [thanks to the keymon](https://github.com/OnionUI/Onion/commit/f7a42ca102f96172ccdc6b8e4c24f4acc84756bf).

**Comment by steward-fu** [comment]
@schmurtzm 
Good, thanks for your information.
