### ISSUE TITLE
[Feature Request] restore the display of the resolution for each mode in display menu

### ISSUE THREAD

**Issue by schmurtzm** [steward-fu/nds_miyoo#40]
V1.6 screenshot :
![image](https://github.com/steward-fu/nds_miyoo/assets/7110113/30be21af-3ef9-47c6-b8b1-dcc8d5647829)

This resolution menu is not available anymore in the v1.7 : 
![menu1 7](https://github.com/steward-fu/nds_miyoo/assets/7110113/6ec9d0b9-bd7b-4a79-b2a0-b1ec17743c1e)

I think that this resolution is useful (to check if the MM v4 is really in 752 x 560 for example).

**Comment by steward-fu** [comment]
commit: https://github.com/steward-fu/nds_miyoo/commit/06b78bdc8d9b958c928964558f6c4123d08efd20

**Comment by schmurtzm** [comment]
Thank you for the restoration of this information, I close this one. 👍🏻
